### ISSUE TITLE
Feature request: Convolve existing impulses with generated impulse

### ISSUE THREAD

**Issue by peteallenm** [brummer10/SpecMatch#1]
Awesome to see you've updated specmatch!! I've been using it for years, find it really helpful, and have been meaning to update it to python3 but never got around to it (In the meantime I've been using the old guitarix version in a docker container).

Something I've been meaning to implement, but want to check I'm on the right track before doing it:
 My usecase for specmatch has often been to compare my guitar tone with a reference recording, and then update existing cabinet IR's to make a closer match. To do this i've convolved the existing cabinet IR I've been using with the specmatch generated one, as IIRC that multiplies in the frequency domain (i.e. applies the EQ of the generated impulse).

This has at times been really powerful, but at times has not worked as I expected (The generated IRs didn't sound right). Is my methodology correct? If so I intend to take a stab at implementing this directly in specmatch to make the process quicker.

**Comment by brummer10** [comment]
When you using a recording output from guitarix as source, including the cabinet IR, the  generated IR should just replace the previous used cabinet IR. 
If the outcome didn't sound right, it often helps to enlarge the generated IR. I got good results from generated IR files with size 25000 instead 3500. As larger the files as finer graduated the frequency bins, because SpecMatch generate smoothed IR's.
Note, as larger the generated IR file as lower the dBFS level should be set. For IR files with size 25000 I using arpond -35  to  -40 dBFS for normalisation.

**Comment by peteallenm** [comment]
That's really neat that it replaces the IR. So does it convolve the existing IR with the generated one?

I unfortunately don't use guitarix for my live sound, I use a standalone multifx. (NAM support is really tempting, but I would want to build a robust, bulletproof rig that I haven't got time for at the moment).
Is there a way of doing the same thing for standalone IR's?

Thank you for the hints about how to get good results, I will try that.

**Comment by brummer10** [comment]
> Is there a way of doing the same thing for standalone IR's?

That's exactly what this new version is about. It is completely u-bounded from guitarix and it's main feature is to generate stand-alone Impulse Response Files by compare the Frequency Spectrum from a Source and a destination file. Source and destination been requested in wav format, File size didn't really matter.

**Comment by peteallenm** [comment]
Aaah, I think I've misunderstood how to use it: I've been comparing the output from my rig including impulse with the reference, but I guess I should be comparing the output without IR to the reference and using the generated IR as my new speaker impulse.
